name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  web-deploy:
    needs: []
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: yurucam/deploy-cloudflare-pages@main
        with:
          account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          working-directory: .
          project-name: bass-fretboard-trainer
          output-directory: dist
